FROM node:18-alpine
WORKDIR /app

# Copy pre-built application
COPY .next ./.next
COPY public ./public
COPY package*.json ./
COPY node_modules ./node_modules

# Runtime environment variables
ENV NODE_ENV=production
ENV NEXT_PUBLIC_AUTH_ENABLED=true
ENV NEXT_PUBLIC_ENABLE_STREAMING=true
ENV NEXT_PUBLIC_LLM_ROUTER_ENDPOINT=https://hdviynn2m4.execute-api.us-east-1.amazonaws.com/prod/proxy/llm
ENV API_GATEWAY_URL=https://api.hfu-amplify.org

EXPOSE 3000
CMD ["npm", "start"]
